name: Android APK (arm64 debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Proje dosyalarını indir
        uses: actions/checkout@v4

      - name: Flutter kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: JDK 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - name: Android projesini oluştur
        run: flutter create . --platforms=android --org com.w3ruslan --project-name surplace_pos --overwrite

      # ---- Gradle ayarlarını güvene al (HEREDOC ile) ----
      - name: Gradle repo ve çözümleme ayarlarını yaz
        shell: bash
        run: |
          set -euo pipefail
          # settings.gradle dosyasını baştan yaz
          cat > android/settings.gradle <<'EOF'
          pluginManagement {
            repositories {
              google()
              mavenCentral()
              gradlePluginPortal()
            }
          }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories {
              google()
              mavenCentral()
            }
          }
          rootProject.name = "surplace_pos"
          include(":app")
          EOF
          # android/build.gradle içine (yoksa) allprojects + repositories + resolutionStrategy ekle
          if ! grep -q "allprojects[[:space:]]*{" android/build.gradle; then
            cat >> android/build.gradle <<'EOF'
          allprojects {
            repositories {
              google()
              mavenCentral()
            }
            configurations.all {
              resolutionStrategy {
                // Kotlin tek sürüm zorla (duplicate class hatasını önler)
                force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
                force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'
              }
            }
          }
          EOF
          fi

      - name: AndroidManifest’e INTERNET izni ekle
        shell: bash
        run: |
          set -euo pipefail
          MANIFEST=android/app/src/main/AndroidManifest.xml
          sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET" />\
              <application#' "$MANIFEST"

      - name: Bağımlılıkları indir
        run: flutter pub get

      - name: APK oluştur (arm64 debug)
        run: flutter build apk --debug --target-platform=android-arm64 --no-shrink

      - name: APK’yi artefact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
