name: Android APK (arm64 debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Proje Dosyalarini Indir
        uses: actions/checkout@v4

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Android Projesini Olustur
        run: flutter create . --platforms=android --org com.w3ruslan --project-name surplace_pos --overwrite

      # --- SİZİN TALİMATINIZLA EKLENEN YENİ DÜZELTMELER ---
      - name: Gradle Adreslerini Garanti Altina Al (settings.gradle + build.gradle)
        run: |
          # settings.gradle: pluginManagement + dependencyResolutionManagement
          cat > android/settings.gradle <<'EOF'
          pluginManagement {
            repositories {
              google()
              mavenCentral()
              gradlePluginPortal()
            }
          }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories {
              google()
              mavenCentral()
            }
          }
          rootProject.name = "surplace_pos"
          include(":app")
          EOF
          # project-level build.gradle: allprojects { repositories { ... } }
          if ! grep -q "allprojects" android/build.gradle; then
            cat >> android/build.gradle <<'EOF'
            allprojects {
              repositories {
                google()
                mavenCentral()
              }
            }
            EOF
          fi
          
      - name: Kotlin Surumunu Hizala ve Tek Surumu Zorla
        run: |
          FILE=android/build.gradle
          # Eski şablonlarda varsa ext.kotlin_version'ı güncelle
          if grep -q "ext.kotlin_version" "$FILE"; then
            sed -i "s/ext.kotlin_version *= *'.*'/ext.kotlin_version = '1.9.24'/" "$FILE"
          fi
          # Bütün modüllerde aynı stdlib sürümünü zorla (duplicate class'ı engeller)
          if ! grep -q "resolutionStrategy" "$FILE"; then
            cat >> android/build.gradle <<'EOF'
            allprojects {
              configurations.all {
                resolutionStrategy {
                  force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
                  force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'
                }
              }
            }
            EOF
          fi
      # --- DÜZELTMELERİN SONU ---

      - name: INTERNET Iznini Ekle
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET" />\n    <application#' "$MANIFEST"
          
      - name: Bagimliliklari Yukle
        run: flutter pub get
        
      - name: APK Olustur (arm64 debug)
        run: flutter build apk --debug --target-platform=android-arm64 --no-shrink
        
      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
