name: Android APK (arm64 release)

on:
  workflow_dispatch: {}   # Manuel çalıştırma için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"   # stabil bir sürüm
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      # Repo’da android klasörü yok. Eksik platformu otomatik oluştur.
      - name: Create Android platform
        run: flutter create . --platforms=android

      # Release’te ağ yazdırma çalışsın diye INTERNET iznini Manifest’e ekle.
      - name: Add INTERNET permission to AndroidManifest
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          if ! grep -q "android.permission.INTERNET" "$MANIFEST"; then
            sed -i '0,/<manifest/{s//&\
    <uses-permission android:name="android.permission.INTERNET" \/>/}' "$MANIFEST"
          fi
          echo "Final manifest:"
          cat $MANIFEST

      - name: Build APK (arm64 only)
        run: |
          flutter build apk --release \
            --target-platform=android-arm64 --split-per-abi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
