name: Android APK (arm64 debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Proje Dosyalarini Indir
        uses: actions/checkout@v4

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Android Projesini Olustur
        run: flutter create . --platforms=android --org com.w3ruslan --project-name surplace_pos --overwrite

      # --- HERE-DOC YOK, printf ile yaziyoruz ---
      - name: Gradle Adreslerini Garanti Altina Al (settings.gradle + build.gradle)
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p android

          # settings.gradle: pluginManagement + dependencyResolutionManagement
          SETTINGS_FILE=android/settings.gradle
          printf '%s\n' \
'pluginManagement {' \
'  repositories {' \
'    google()' \
'    mavenCentral()' \
'    gradlePluginPortal()' \
'  }' \
'}' \
'dependencyResolutionManagement {' \
'  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)' \
'  repositories {' \
'    google()' \
'    mavenCentral()' \
'  }' \
'}' \
'rootProject.name = "surplace_pos"' \
'include(":app")' \
          > "$SETTINGS_FILE"

          # project-level build.gradle: allprojects { repositories { ... } } yoksa ekle
          if ! grep -q "allprojects" android/build.gradle; then
            printf '%s\n' \
'allprojects {' \
'  repositories {' \
'    google()' \
'    mavenCentral()' \
'  }' \
'}' \
            >> android/build.gradle
          fi

      - name: Kotlin Surumunu Hizala ve Tek Surumu Zorla
        shell: bash
        run: |
          set -euo pipefail
          FILE=android/build.gradle

          # Eski şablonlarda varsa ext.kotlin_version'ı 1.9.24'e çek
          if grep -q "ext.kotlin_version" "$FILE"; then
            sed -i "s/ext.kotlin_version *= *'.*'/ext.kotlin_version = '1.9.24'/" "$FILE"
          fi

          # resolutionStrategy yoksa ekle (tek stdlib sürümü)
          if ! grep -q "resolutionStrategy" "$FILE"; then
            printf '%s\n' \
'allprojects {' \
'  configurations.all {' \
'    resolutionStrategy {' \
"      force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'" \
"      force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'" \
'    }' \
'  }' \
'}' \
            >> "$FILE"
          fi

      - name: INTERNET Iznini Ekle
        shell: bash
        run: |
          set -euo pipefail
          MANIFEST=android/app/src/main/AndroidManifest.xml
          sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET" />\
    <application#' "$MANIFEST"

      - name: Bagimliliklari Yukle
        run: flutter pub get

      - name: APK Olustur (arm64 debug)
        run: flutter build apk --debug --target-platform=android-arm64 --no-shrink

      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
