name: Android APK (arm64 release)

on:
  workflow_dispatch: {}   # Elle çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      # Repo içeriğini al
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Disable analytics
        run: flutter config --no-analytics

      # Ağ takılırsa "pub get" 5 kez dene
      - name: Install dependencies (retry)
        run: |
          for i in {1..5}; do
            flutter pub get && break
            echo "Retrying flutter pub get ($i/5)..."
            sleep 8
          done

      # >>> ÖNEMLİ: android/ klasörü yoksa oluşturur
      - name: Ensure Android platform exists
        run: |
          if [ ! -f android/app/src/main/AndroidManifest.xml ]; then
            echo "android/ yok, şimdi oluşturuyorum..."
            flutter create --platforms=android .
          fi
          ls -la android/app/src/main || true

      # (İsteğe bağlı) INTERNET izni ekle – yazıcı/TCP için lazım olabilir
      - name: Add INTERNET permission to AndroidManifest
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          if ! grep -q 'android.permission.INTERNET' "$MANIFEST"; then
            awk '
              /<manifest/ && !added { print; print "    <uses-permission android:name=\"android.permission.INTERNET\"/>"; added=1; next }
              { print }
            ' "$MANIFEST" > tmp.xml && mv tmp.xml "$MANIFEST"
          fi
          head -n 40 "$MANIFEST"

      # Sadece ARM64 APK üret (Galaxy Tab A9+ için ideal)
      - name: Build APK (arm64)
        run: |
          flutter build apk --release --target-platform=android-arm64

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-arm64
          path: build/app/outputs/flutter-apk/*.apk
