name: Android APK (arm64 debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Kodu al
      - uses: actions/checkout@v4

      # 2) JDK 17 (Java Geliştirme Kiti)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3) Android SDK (Android Geliştirme Kiti)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses || true

      # 4) Flutter SDK (Flutter Geliştirme Kiti)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.3'   # Senin bilgisayarındaki sürümle aynı
          cache: true

      # 5) Ortam görünürlüğü (bir sorun olursa diye kontrol için)
      - name: Flutter doctor
        run: flutter doctor -v

      - name: Show pubspec.yaml
        run: cat pubspec.yaml

      - name: Show main.dart head
        run: sed -n '1,60p' lib/main.dart

      # 6) Eğer android klasörü yoksa oluştur
      - name: Create Android folder if missing
        run: |
          if [ ! -d android ]; then
            flutter create . --platforms=android --org com.w3ruslan --project-name surplace_pos
          else
            echo "android/ already exists; skipping flutter create"
          fi
            
      # 7) INTERNET izni (manifest'e ekle)
      - name: Add INTERNET permission
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          grep -q 'android.permission.INTERNET' "$MANIFEST" || \
            sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET" />\n    <application#' "$MANIFEST"
            
      # 8) Bağımlılıkları indir
      - name: Get dependencies
        run: flutter pub get

      # 9) Analiz (DOĞRU KOMUT: FLUTTER ANALYZE)
      - name: Analyze code
        run: flutter analyze

      # 10) Temizle (isteğe bağlı ama iyi bir alışkanlık)
      - name: Clean project
        run: flutter clean

      # 11) APK üret
      - name: Build APK (verbose)
        run: flutter build apk --debug --target-platform=android-arm64 --no-shrink --verbose

      # 12) APK’yı indirilebilmesi için yükle
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
